title: B.L MOTORSPORT
email: contact@bl-motorsport.com
description: "Atelier de mécanique de précision."
# IMPORTANT : baseurl doit correspondre au nom de ton dépôt
baseurl: "/bl-motorsport"
url: "https://duvaldvl.github.io"

theme: jekyll-theme-prime

# Configuration Multilingue
languages: ["fr", "en", "de", "it"]
default_lang: "fr"

markdown: kramdown
permalink: pretty

# Exclusions pour accélérer le build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Données Entreprise
company:
  name: "B.L MOTORSPORT"
  address: "679 route de Plan Mouillé"
  zip: "74920"
  city: "Combloux"
  phone: "+33 6 60 82 51 57"
  whatsapp_link: "https://wa.me/33660825157"

sass:
  style: compressed
