title: B.L Motorsport
description: "Atelier de mécanique de prestige et préparation compétition (WEC). Spécialiste Porsche, Ferrari, BMW. Service voiturier à Megève et Chamonix."
# Ton dossier GitHub actuel :
baseurl: "/bl-motorsport"
# Ton url utilisateur :
url: "https://duvaldvl.github.io"

markdown: kramdown
permalink: pretty
theme: null

# DONNÉES ENTREPRISE
company:
  name: "B.L MOTORSPORT"
  address: "679 route de Plan Mouillé"
  zip: "74920"
  city: "Combloux"
  phone: "+33 6 60 82 51 57"
  # MISE À JOUR EMAIL
  email: "bastienlefebvre.motorsport@gmail.com" 
  whatsapp_link: "https://wa.me/33660825157"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
