title: BL Motorsport
description: Atelier Mecanique
baseurl: "/bl-motorsport"
url: "https://duvaldvl.github.io"
markdown: kramdown
permalink: pretty
theme: jekyll-theme-prime
plugins:
  - jekyll-seo-tag
